services:
  db:
    image: mariadb:11.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rustdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3356:3306"
    networks:
      - rust_network

  rust:
    image: rust:latest
    volumes:
      - .:/usr/src/
    working_dir: /usr/src/
    command: bash -c "cd source && cargo run"
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    links:
      - db
    tty: true
    networks:
      - rust_network
    ports:
      - 8090:8000
networks:
  rust_network:
    driver: bridge
